// Lightbox functionality
let currentImageIndex = 0;
let images = [];

// --- Dynamic Data Extraction ---
function initializeGallery() {
    // Get all menu item elements
    const menuItems = document.querySelectorAll('.menu-item');
    
    // Map the necessary data from each item into the 'images' array
    images = Array.from(menuItems).map(item => {
        const imgElement = item.querySelector('img');
        const priceElement = item.querySelector('input[type="radio"]');
        const descElement = item.querySelector('p small');

        // Capture data, handling cases where elements might be missing
        const src = imgElement ? imgElement.src : '';
        const alt = imgElement ? imgElement.alt : 'Menu Item';
        const price = priceElement ? priceElement.value : 'Price N/A';
        const description = descElement ? descElement.textContent : 'No description.';

        return {
            src: src,
            // Create a rich caption combining Price, Alt, and Description
            caption: `${price} - ${alt}. Ingredients: ${description}`,
        };
    });

    // Attach click listener to each menu item's entire div
    menuItems.forEach((item, index) => {
        item.onclick = function() {
            // Find the image src dynamically when clicked
            const src = item.querySelector('img').src;
            // The caption is generated by the images array, find it by src
            const caption = images[index].caption; 
            openLightbox(src, caption);
        };
    });
}

// Run the initialization when the page loads
document.addEventListener('DOMContentLoaded', initializeGallery);


// --- Lightbox Functions ---

function openLightbox(src, caption) {
    const lightbox = document.getElementById('lightbox');
    const lightboxImg = document.getElementById('lightbox-img');
    const lightboxCaption = document.getElementById('lightbox-caption');
    
    // Find the index of the clicked image using the src
    currentImageIndex = images.findIndex(img => img.src === src);
    
    if (currentImageIndex === -1) return;

    // Display the image and caption
    lightboxImg.src = images[currentImageIndex].src;
    lightboxCaption.textContent = images[currentImageIndex].caption; 
    
    lightbox.style.display = 'flex';
    document.body.style.overflow = 'hidden';
}

function closeLightbox() {
    const lightbox = document.getElementById('lightbox');
    lightbox.style.display = 'none';
    document.body.style.overflow = 'auto';
}

function changeImage(direction) {
    currentImageIndex += direction;
    
    // Wrap around if at beginning or end
    if (currentImageIndex < 0) {
        currentImageIndex = images.length - 1;
    } else if (currentImageIndex >= images.length) {
        currentImageIndex = 0;
    }
    
    const lightboxImg = document.getElementById('lightbox-img');
    const lightboxCaption = document.getElementById('lightbox-caption');
    
    lightboxImg.src = images[currentImageIndex].src;
    lightboxCaption.textContent = images[currentImageIndex].caption;
}

// Close lightbox when clicking outside the image
document.getElementById('lightbox').addEventListener('click', (e) => {
    if (e.target === document.getElementById('lightbox')) {
        closeLightbox();
    }
});

// Optional: Close on Escape key press
document.addEventListener('keydown', function(e) {
    if (e.key === "Escape" && document.getElementById('lightbox').style.display === "flex") {
        closeLightbox();
    }
});